#!/usr/bin/env python3
"""Source-pinned OCCT revolve history beside the kernel's cone histories (S3).

`occt_revolve_oracle.cpp` revolves each cone's meridian polygon a full turn
with BRepPrimAPI_MakeRevol and reports BRepTools_History and MakeRevol's
FirstShape/LastShape for every meridian subshape. The Rust histories are
first certified equal to the independent enumeration
(`identity_reference.cone_entities`, through the identity and history
fixtures and tests); `examples/cone_probe.rs` prints them with geometric
signatures of their targets.

The kernel's meridian is boundary 0, the polygon (0, 0), (r1, 0), (r2, h),
(0, h) with segment j from point j to j+1. A native meridian vertex maps to
the kernel's index by its radius and height (an apex is its rim point, 1 or
2), a native edge to the segment between its ends (both on the axis: 3).
Documented correspondences:

    rim vertex k: Generated circle      -> the ring generated by P0.vk
                  Generated degenerated -> the apex generated by P0.vk (the
                                           pole OCCT closes with that edge)
                  First/LastShape       -> the same apex, or a seam vertex
    segment 1:    Generated cone face   -> the wall generated by P0.s1

OCCT reports the axis, the radial segments 0 and 2 and the meridian face
deleted: `IsDeleted` is `!IsUsed` (BRepPrimAPI_MakeRevol.cxx) and a full,
closed revolution leaves the discs and the solid unused, though both are in
the result. The kernel's cap relations (P0.s0, P0.s2) and region relation
(P0.b0) are therefore verified against those unreached outputs: each cap
must equal a native face no query reaches, the region the native solid.
First/LastShape of the other meridian subshapes are copies the closed
revolution leaves out of its result (`outside`), or its seam and seam
vertices (`structure`, S rows). A case matches when every native query maps
by these rules to one kernel relation with an equal signature, every kernel
relation is reached or verified, every native output is reached, structure
or verified, the synthesized counts equal the native N row and the native
solid is valid. The one reviewable difference is `surface_of_revolution`:
MakeRevol types a revolved line as a cone only when the cosine of its
semi-angle is at most 1 - Precision::Confusion()
(GeomAdaptor_SurfaceOfRevolution::GetType), and otherwise builds a
Geom_SurfaceOfRevolution of the same line, which MakeCone and the kernel
make a cone; such a wall must still match by area and centre, and needs a
fingerprinted review in `occt-revolve-history-divergences.json`.

`--capture` records the native observations in
`fixtures/occt-revolve-history-capture`; REVIEW_NOTES.md R11 says what
existed when it was taken. Every later run must reproduce them.
"""
import argparse
import json
from pathlib import Path
import subprocess
import sys

import mpmath as mp

from build_pinned_occt import SOURCE, digest
from compare_brep import review_for, run, sha, write
from compare_degree_elevation import verify_sdk
from compare_occt import ROOT
import compare_primitives
import generate_primitive_fixtures
from primitive_reference import axes

CAPTURE = ROOT/'rust/fixtures/occt-revolve-history-capture'
REVIEWS = ROOT/'rust/fixtures/occt-revolve-history-divergences.json'
REVIEWABLE = {'surface_of_revolution'}
SOURCE_FILE = ROOT/'rust/tools/occt_revolve_oracle.cpp'
# Relative to the case's size (points), its square (areas) or cube
# (volumes), as compare_primitives.BOUND.
BOUND = 1e-9
# The capture reproduces to the last bits of libm between platforms.
REPRODUCE = 2.0**-40


def build(prefix, output):
    saved = compare_primitives.SOURCE_FILE
    compare_primitives.SOURCE_FILE = SOURCE_FILE
    try:
        return compare_primitives.build(prefix, output)
    finally:
        compare_primitives.SOURCE_FILE = saved


def signature(words):
    """(kind, numbers) of a signature's words: V, E line|circle|degenerated,
    F type, S."""
    if words[0] in ('E', 'F'):
        return (words[0]+' '+words[1], [float(x) for x in words[2:]])
    return (words[0], [float(x) for x in words[1:]])


def parse_native(text):
    out, case = {}, None
    for line in text.splitlines():
        w = line.split()
        if w[0] == 'R':
            case = out.setdefault(w[1], {'face_valid': w[2], 'inputs': {}, 'queries': [], 'deleted': [],
                                         'outputs': [], 'structure': [], 'degenerated': []})
        elif w[0] == 'I':
            case['inputs'][(w[1], int(w[2]))] = signature(w[3:])
        elif w[0] == 'Q':
            label = (w[1], int(w[2]))
            if w[3] == 'deleted':
                case['deleted'].append(label)
            else:
                case['queries'].append((label, w[3], None if w[4] == 'null' else signature(w[4:])))
        elif w[0] == 'B':
            case['body'], case['valid'] = signature(w[1:-1]), w[-1] == '1'
        elif w[0] == 'O':
            case['outputs'].append((signature(w[1:-1]), w[-1]))
        elif w[0] == 'N':
            case['counts'] = [int(x) for x in w[1:]]
        elif w[0] == 'S':
            case['structure'].append(signature(w[1:]))
        elif w[0] == 'D':
            case['degenerated'].append(signature(w[1:]))
        elif w[0] != 'end':
            raise ValueError('malformed native line '+line)
    return out


def parse_rust(text):
    out, case = {}, None
    for line in text.splitlines():
        w = line.split()
        if w[0] == 'case':
            case = out.setdefault(w[1], {'relations': []})
        elif w[0] == 'C':
            case['counts'] = [int(x) for x in w[1:]]
        elif w[0] == 'G':
            case['relations'].append((w[1], w[2], signature(w[3:])))
        elif w[0] == 'B':
            case['body'] = signature(w[1:])
        elif w[0] != 'end':
            raise ValueError('malformed Rust line '+line)
    return out


def same(a, b, size):
    """Equal signatures within BOUND: points against the size, areas and
    volumes against their value or the size squared or cubed."""
    if a is None or b is None or a[0] != b[0] or len(a[1]) != len(b[1]):
        return False
    kind, x, y = a[0], a[1], b[1]
    scales = [size]*len(x)
    if kind.startswith('F'):
        scales[0] = max(abs(y[0]), size**2)
    elif kind == 'S':
        scales[0] = max(abs(y[0]), size**3)
    return all(abs(p-q) <= BOUND*s for p, q, s in zip(x, y, scales))


def meridian(c, size):
    """Point -> the kernel's meridian vertex index, or None."""
    o, x, y, n = axes(c)
    r1, r2, h = mp.mpf(c.r1), mp.mpf(c.r2), mp.mpf(c.height)

    def index(p):
        d = [mp.mpf(p[i])-o[i] for i in range(3)]
        z = sum(d[i]*n[i] for i in range(3))
        r = mp.sqrt(max(sum(d[i]**2 for i in range(3))-z**2, 0))
        near = lambda a, b: abs(a-b) <= BOUND*size
        found = [k for k, (rk, zk) in enumerate([(0, 0), (r1, 0), (r2, h), (0, h)]) if near(r, rk) and near(z, zk)]
        # An apex is its rim point.
        found = [k for k in found if not (k == 0 and 1 in found) and not (k == 3 and 2 in found)]
        return found[0] if len(found) == 1 else None
    return index


def segment(a, b):
    if a is None or b is None:
        return None
    if {a, b} in ({0, 1}, {1, 2}, {2, 3}):
        return min(a, b)
    # Both ends on the axis: (3, 0), or an apex and the other axis point.
    return 3


def compare(c, native, rust, size):
    """Sorted failure classes and the case's classification counts."""
    failures, stats = set(), {'mapped': 0, 'structure': 0, 'outside': 0, 'verified_unreported': 0}
    index = meridian(c, size)
    labels = {}
    for (kind, j), sig in native['inputs'].items():
        if kind == 'vertex':
            labels[(kind, j)] = ('v', index(sig[1]))
        elif kind == 'edge':
            p = sig[1]
            labels[(kind, j)] = ('s', segment(index(p[0:3]), index(p[6:9])))
        else:
            labels[(kind, j)] = ('b', 0)
    if any(v[1] is None for v in labels.values()):
        return ['meridian_unmapped'], stats
    relations = rust['relations']
    reached = [False]*len(relations)

    def find(parent, want, role=None):
        hits = [k for k, (p, r, sig) in enumerate(relations)
                if p == parent and (role is None or r == role) and same(want, sig, size)]
        return hits[0] if len(hits) == 1 else None

    structure = native['structure']
    in_result = [sig for sig, _ in native['outputs']]
    for label, query, sig in native['queries']:
        element, k = labels[label]
        parent = f'P0.{element}{k}'
        if query == 'gen':
            hit = None
            if element == 'v' and sig[0] == 'E circle':
                hit = find(parent, sig)
            elif element == 'v' and sig[0] == 'E degenerated':
                hit = find(parent, ('V', sig[1]), 'apex')
            elif element == 's' and k == 1 and sig[0] == 'F cone':
                hit = find(parent, sig, 'wall')
            elif element == 's' and k == 1 and sig[0] == 'F revolution':
                # MakeRevol's surface type for a line nearly parallel to the
                # axis: the same point set, reviewable.
                hit = find(parent, ('F cone', sig[1]), 'wall')
                failures.add('surface_of_revolution')
            if hit is None:
                failures.add('unmapped_generated')
            else:
                reached[hit] = True
                stats['mapped'] += 1
        elif query in ('first', 'last'):
            if sig is None:
                failures.add('null_first_or_last')
            elif element == 'v' and find(parent, sig, 'apex') is not None:
                # The apex: OCCT's structure rule lists it, as only the seam
                # and the degenerated edge use it; the kernel's pole vertex.
                reached[find(parent, sig, 'apex')] = True
                stats['mapped'] += 1
            elif any(same(sig, s, size) for s in structure):
                stats['structure'] += 1
            elif not any(same(sig, s, size) for s in in_result):
                stats['outside'] += 1
            else:
                failures.add('unmapped_first_or_last')
        else:
            failures.add('unexpected_'+query)
    # Deleted: the axis, the radial segments and the face, exactly.
    deleted = sorted(labels[label] for label in native['deleted'])
    expected_deleted = sorted([('b', 0), ('s', 3)]+[('s', s) for s, r in ((0, c.r1), (2, c.r2)) if r > 0]
                              + [('v', v) for v, r in ((0, c.r1), (3, c.r2)) if r > 0])
    if deleted != expected_deleted:
        failures.add('deleted_set')
    # The kernel's caps and region against the outputs no query reaches.
    unreached = [sig for sig, reach in native['outputs'] if reach == 'none']
    covered = set()
    for k, (parent, role, sig) in enumerate(relations):
        if reached[k]:
            continue
        if role in ('start_cap', 'end_cap'):
            hits = [i for i, s in enumerate(unreached) if same(sig, s, size) and i not in covered]
            if len(hits) == 1 and ('s', int(parent[-1])) in deleted:
                covered.add(hits[0])
                reached[k] = True
                stats['verified_unreported'] += 1
        elif role == 'region' and ('b', 0) in deleted and same(sig, native['body'], size):
            reached[k] = True
            stats['verified_unreported'] += 1
    if not all(reached):
        failures.add('kernel_relation_unreached')
    if len(covered) != len(unreached):
        failures.add('native_output_uncovered')
    if not same(rust['body'], native['body'], size):
        failures.add('body')
    if native.get('counts') != rust['counts']:
        failures.add('counts')
    if not native['valid']:
        failures.add('native_invalid')
    return sorted(failures), stats


def reproduces(observed, captured, size):
    """The same rows, numbers within REPRODUCE of the case's size."""
    a, b = observed.split(), captured.split()
    if len(a) != len(b):
        return False
    for x, y in zip(a, b):
        if x == y:
            continue
        try:
            if abs(float(x)-float(y)) > REPRODUCE*max(size, abs(float(y))):
                return False
        except ValueError:
            return False
    return True


def blocks(text):
    out, name, rows = {}, None, []
    for line in text.splitlines():
        if line.startswith('R '):
            name, rows = line.split()[1], []
        rows.append(line)
        if line == 'end':
            out[name] = '\n'.join(rows)
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--occt-root', type=Path, required=True)
    parser.add_argument('--sdk-manifest', type=Path, required=True)
    parser.add_argument('--output', type=Path, default=ROOT/'target/revolve-history-oracle')
    parser.add_argument('--capture', action='store_true')
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    verify_sdk(args.occt_root.resolve(), args.sdk_manifest)
    cases = generate_primitive_fixtures.generate()['primitive-cases.txt']
    if cases != (ROOT/'rust/fixtures/primitive-cases.txt').read_text():
        raise ValueError('independent fixture regeneration changed: primitive-cases.txt')
    executable, env, loaded, command = build(args.occt_root.resolve(), output)
    record = run(executable, cases.rstrip('\n'), env)
    if record['exit_code'] != 0:
        raise SystemExit('native run failed: '+json.dumps(record)[:2000])
    oracle = next(iter(record['stderr'].splitlines()), None)
    if args.capture:
        status = subprocess.run(['git', 'status', '--porcelain', '--', 'rust'], cwd=ROOT, text=True,
                                capture_output=True, check=True).stdout.splitlines()
        CAPTURE.mkdir(parents=True, exist_ok=True)
        (CAPTURE/'inputs.txt').write_text(cases)
        (CAPTURE/'native.txt').write_text(record['stdout'])
        (CAPTURE/'oracle.cpp').write_text(SOURCE_FILE.read_text())
        revision = subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True, capture_output=True,
                                  check=True).stdout.strip()
        write(CAPTURE/'capture.json', {
            'source_reference': SOURCE, 'oracle': oracle, 'rust_revision': revision,
            'platform': sys.platform, 'rust_cone_builder_uncommitted': True,
            'python_history_enumeration_exists': False, 'rust_worktree_uncommitted': status,
            'sdk_manifest_sha256': digest(args.sdk_manifest), 'input_sha256': digest(CAPTURE/'inputs.txt'),
            'probe_source_sha256': digest(CAPTURE/'oracle.cpp'),
            'observations_sha256': digest(CAPTURE/'native.txt')})
    metadata = json.loads((CAPTURE/'capture.json').read_text())
    for key, name in [('input_sha256', 'inputs.txt'), ('probe_source_sha256', 'oracle.cpp'),
                      ('observations_sha256', 'native.txt')]:
        if metadata[key] != digest(CAPTURE/name):
            raise ValueError('captured evidence changed: '+name)
    if (CAPTURE/'inputs.txt').read_text() != cases:
        raise ValueError('the capture is not of these cases')
    subprocess.run(['cargo', '+stable', 'build', '--release', '--locked', '--example', 'cone_probe'],
                   cwd=ROOT, check=True)
    probe = subprocess.run([str(ROOT/'target/release/examples/cone_probe')], input=cases, text=True,
                           capture_output=True, timeout=600, check=True).stdout
    (output/'rust.txt').write_text(probe)
    (output/'native.txt').write_text(record['stdout'])
    native, rust = parse_native(record['stdout']), parse_rust(probe)
    captured = blocks((CAPTURE/'native.txt').read_text())
    observed = blocks(record['stdout'])
    size = compare_primitives.sizes()
    reviews = json.loads(REVIEWS.read_text())['reviews'] if REVIEWS.exists() else []
    inputs = {line.split()[1]: line for line in cases.splitlines()}
    report = {'source_reference': SOURCE, 'oracle': oracle, 'cases': len(size), 'matches': [],
              'reviewed_differences': [], 'failures': [], 'classified': {}}
    for c in generate_primitive_fixtures.corpus():
        found, stats = compare(c, native[c.name], rust[c.name], size[c.name])
        if not reproduces(observed[c.name], captured[c.name], size[c.name]):
            found = sorted(set(found) | {'capture_not_reproduced'})
        for key, value in stats.items():
            report['classified'][key] = report['classified'].get(key, 0)+value
        evidence = {'case': c.name, 'source_reference': SOURCE, 'oracle': oracle,
                    'input_sha256': sha(inputs[c.name]+'\n'),
                    'native_stdout_sha256': sha(observed[c.name]+'\n'), 'differences': found}
        review = review_for(evidence, reviews) if found and set(found) <= REVIEWABLE else None
        if review:
            report['reviewed_differences'].append(dict(evidence, reason=review['reason']))
        elif found:
            report['failures'].append(evidence)
        else:
            report['matches'].append(c.name)
    write(output/'report.json', report)
    write(output/'capture.json', {'source_reference': SOURCE, 'oracle': oracle, 'loaded_libraries': loaded,
                                  'build_command': command, 'source_sha256': digest(SOURCE_FILE)})
    print(json.dumps({k: len(v) if isinstance(v, list) else v for k, v in report.items()}, indent=2))
    if report['failures']:
        print(json.dumps(report['failures'][:5], indent=1)[:4000])
        raise SystemExit(1)


if __name__ == '__main__':
    main()
